name: CD Deployment

on:
  push:
    branches:
      - develop
      - main

jobs:

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose up -d --build

      - name: Run migration
        run: docker compose exec backend npm run migration:run

      - name: Health check frontend
        run: |
          sleep 15
          curl -f http://localhost:3000

      - name: Health check backend
        run: |
          curl -f http://localhost:3001/health


  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy production
        run: docker compose -f docker-compose.prod.yml up -d --build

      - name: Run migration
        run: docker compose -f docker-compose.prod.yml exec backend npm run migration:run

      - name: Health check
        run: |
          sleep 15
          curl -f http://localhost:3000
          curl -f http://localhost:3001/health
